// This is just a place holder to test with,
// later we will load all the levels by parsing the xml.
import { Color, Modifier, Square } from "@/components/Square/Square";

export const level = [
  [
    <Square
      color={Color.blue}
      targetColor={Color.blue}
      modifier={Modifier.bomb}
    />,
    <Square
      color={Color.red}
      targetColor={Color.red}
      modifier={Modifier.circle}
    />,
    <Square
      color={Color.yellow}
      targetColor={Color.yellow}
      modifier={Modifier.left}
    />,
    <Square
      color={Color.green}
      targetColor={Color.green}
      modifier={Modifier.rotateDown}
    />,
    <Square
      color={Color.yellow}
      targetColor={Color.yellow}
      modifier={Modifier.left}
    />,
  ],
  [
    <Square
      color={Color.none}
      targetColor={Color.blue}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
  ],
  [
    <Square
      color={Color.none}
      targetColor={Color.blue}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.red}
      targetColor={Color.red}
      modifier={Modifier.down}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.green}
      modifier={Modifier.none}
    />,
  ],
  [
    <Square
      color={Color.none}
      targetColor={Color.blue}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.red}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.green}
      modifier={Modifier.none}
    />,
  ],
  [
    <Square
      color={Color.blue}
      targetColor={Color.blue}
      modifier={Modifier.up}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.red}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.none}
      targetColor={Color.none}
      modifier={Modifier.none}
    />,
    <Square
      color={Color.green}
      targetColor={Color.green}
      modifier={Modifier.up}
    />,
  ],
];
