import { useRouter } from 'next/router';
import Head from 'next/head'

export default function Header() {
  // We can't use next/link to automatically add the basePath because that will
  // create an <a> tag instead of a <link> tag. So we ue react router to add the
  // basePath to the favicon
  const router = useRouter();
  const faviconUrl = `${router.basePath}/favicon.ico`
  return (
    <Head>
      <title>Flowit React</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href={faviconUrl} />
    </Head>
  )
}
